=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/schema/jdbc-service.dtd
<!ELEMENT jdbc-service (jdbc-service-config*, available-conn-handler*)>

<!ELEMENT jdbc-service-config (log-type, log-level, log-location,conn-handler, limit-time, limit-row, conn-param*, description?)>
<!ELEMENT log-type (#PCDATA)>
<!ELEMENT log-level (#PCDATA)>
<!ELEMENT log-location (#PCDATA)>
<!ELEMENT conn-handler (#PCDATA)> <!-- jspeed.base.jdbc.ConnectionHandler interface -->
<!ELEMENT limit-time (#PCDATA)>
<!ELEMENT limit-row (#PCDATA)>
<!ELEMENT conn-param (param-name, param-value)>

<!ELEMENT available-conn-handler (conn-handler, help-page)>
<!ELEMENT help-page (#PCDATA)>

<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST jdbc-service
	defaultElement CDATA #IMPLIED
	verbose (true | false) 'false'>

<!ATTLIST jdbc-service-config
	name CDATA #REQUIRED
	deploy (true | false) 'false'
	loadOnStartup CDATA #IMPLIED
	verbose (true | false) 'false'
	monitor (true | false) 'false'
	lastModified CDATA #IMPLIED
	target CDATA #IMPLIED>

=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/jdbc-service.xml
<?xml version="1.0" encoding="euc-kr"?>
<!-- UTF-8 처占쏙옙 -->

<!DOCTYPE jdbc-service SYSTEM "jdbc-service.dtd">

	<jdbc-service verbose="true" defaultElement="ITPDataSource">

		<jdbc-service-config name="ITPDataSource" deploy="true" loadOnStartup="100" verbose="true" lastModified="1235650047692" target="all.web">
			<log-type>ONLY_CONSOLE</log-type>
			<log-level>DEBUG</log-level>
			<log-location></log-location>
			<conn-handler>jspeed.base.jdbc.DataSourceConnectionHandler</conn-handler>
			<limit-time>100</limit-time>
			<limit-row>100</limit-row>
			<conn-param>
				<param-name>jndi-name</param-name>
				<param-value>AMLDataSource</param-value>
			</conn-param>
			<!--
			<conn-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</conn-param>
		 	-->

		</jdbc-service-config>
	<jdbc-service-config name="AMLDS_ITP" deploy="true" loadOnStartup="100" verbose="true" lastModified="1235650047692" target="all.web">
			<log-type>ONLY_CONSOLE</log-type>
			<log-level>DEBUG</log-level>
			<log-location></log-location>
			<conn-handler>jspeed.base.jdbc.DataSourceConnectionHandler</conn-handler>
			<limit-time>100</limit-time>
			<limit-row>100</limit-row>
			<conn-param>
				<param-name>jndi-name</param-name>
				<param-value>AMLDataSource</param-value>
			</conn-param>
			<!--
			<conn-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</conn-param>
		 	-->

		</jdbc-service-config>

		<!-- <jdbc-service-config name="AMLDS_WF" deploy="true" loadOnStartup="100" verbose="true" lastModified="1235650047692" target="all.web">
			<log-type>ONLY_CONSOLE</log-type>
			<log-level>DEBUG</log-level>
			<log-location></log-location>
			<conn-handler>jspeed.base.jdbc.DataSourceConnectionHandler</conn-handler>
			<limit-time>100</limit-time>
			<limit-row>100</limit-row>
			<conn-param>
				<param-name>jndi-name</param-name>
				<param-value>AMLDS_WF</param-value>
			</conn-param>

			<conn-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</conn-param>


		</jdbc-service-config> -->

		<jdbc-service-config name="jSpeedDataSource" deploy="true" loadOnStartup="100" verbose="true" monitor="true" lastModified="1235650061692" target="all.web">
			<log-type>ONLY_CONSOLE</log-type>
			<log-level>DEBUG</log-level>
			<log-location></log-location>
			<conn-handler>jspeed.base.jdbc.DataSourceConnectionHandler</conn-handler>
			<limit-time>100</limit-time>
			<limit-row>100</limit-row>
			<conn-param>
				<param-name>jndi-name</param-name>
				<param-value>AMLDataSource</param-value>
			</conn-param>
			<!--
			<conn-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</conn-param>
			-->
			<description>DataSource Connection</description>
		</jdbc-service-config>

	</jdbc-service>
