=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/schema/jndi-service.dtd
<!ELEMENT jndi-service (jndi-service-config*, available-environment-param*, relation-service*)>
<!ELEMENT jndi-service-config (log-type, log-level, log-location, env-param+, description?)>
<!ELEMENT env-param (param-name, param-value)>
<!ELEMENT available-environment-param (param-name, default-value, instance-map-name, help-page)>
<!ELEMENT default-value (#PCDATA)>
<!ELEMENT instance-map-name (#PCDATA)>
<!ELEMENT relation-service (service-name,relation-service-name)>
<!ELEMENT service-name (#PCDATA)>
<!ELEMENT relation-service-name (#PCDATA)>

<!ELEMENT log-type (#PCDATA)>
<!ELEMENT log-level (#PCDATA)>
<!ELEMENT log-location (#PCDATA)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT help-page (#PCDATA)>

<!ATTLIST jndi-service
	defaultElement CDATA #IMPLIED
	verbose (true | false) 'false'>
	
<!ATTLIST jndi-service-config
	name CDATA #REQUIRED
	deploy (true | false) 'false'
	loadOnStartup CDATA #IMPLIED
	verbose (true | false) 'false'
	lastModified CDATA #IMPLIED
	target CDATA #IMPLIED>

=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/jndi-service.xml
<?xml version="1.0" encoding="euc-kr"?>

<!-- UTF-8 처占쏙옙 -->

<!DOCTYPE jndi-service SYSTEM "jndi-service.dtd">

	<jndi-service verbose="true" defaultElement="default">

		<jndi-service-config name="default" deploy="true" loadOnStartup="100" verbose="true" lastModified="1106654800235" target="all.all">
			<log-type>ONLY_CONSOLE</log-type>
			<log-level>DEBUG</log-level>
			<log-location></log-location>
			<env-param>
				<param-name>jspeed.instance.key</param-name>
				<param-value>default</param-value>
			</env-param>
		</jndi-service-config>

		<available-environment-param>
			<param-name>Context.INITIAL_CONTEXT_FACTORY</param-name>
			<default-value>weblogic.jndi.WLInitialContextFactory</default-value>
			<instance-map-name></instance-map-name>
			<help-page>/help/base/jndi/environment/environmentHelp.html#java.naming.factory.initial</help-page>
		</available-environment-param>

		<available-environment-param>
			<param-name>Context.PROVIDER_URL</param-name>
			<default-value></default-value>
			<instance-map-name>instance-address</instance-map-name>
			<help-page>/help/base/jndi/environment/environmentHelp.html#java.naming.provider.url</help-page>
		</available-environment-param>

		<available-environment-param>
			<param-name>URL.key</param-name>
			<default-value>t3://</default-value>
			<instance-map-name></instance-map-name>
			<help-page>/help/base/jndi/environment/environmentHelp.html#java.naming.provider.url</help-page>
		</available-environment-param>

		<relation-service>
			<service-name>default</service-name>
			<relation-service-name>default EJB Service</relation-service-name>
		</relation-service>

	</jndi-service>
