=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/schema/log-service.dtd
<!ELEMENT log-service (log-service-config*)>

<!ELEMENT log-service-config (log-location?, log-level?, log-directory?, max-log-size?, show-prefix?, check-param?, log-param*, description?)>
<!ELEMENT log-location (#PCDATA)> <!-- NOT_LOGGING | ONLY_FILE | ONLY_CONSOLE | CONSOLE_FILE -->
<!ELEMENT log-level (#PCDATA)> <!-- ERROR | WARNING | INFO | DEBUG -->
<!ELEMENT log-directory (#PCDATA)>
<!ELEMENT max-log-size (#PCDATA)> <!-- int value, default=50 -->
<!ELEMENT show-prefix (#PCDATA)> <!-- true | false, default=false -->
<!ELEMENT check-param (#PCDATA)> <!-- true | false, default=false -->
<!ELEMENT log-param (param-name, param-value)>

<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST log-service
	defaultElement CDATA #IMPLIED
	verbose (true | false) 'false'>

<!ATTLIST log-service-config
	name CDATA #REQUIRED
	deploy (true | false) 'false'
	loadOnStartup CDATA #IMPLIED
	verbose (true | false) 'false'
	lastModified CDATA #IMPLIED
	target CDATA #IMPLIED>

=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/log-service.xml
<?xml version="1.0" encoding="euc-kr"?>

<!-- UTF-8 처占쏙옙 -->

<!DOCTYPE log-service SYSTEM "log-service.dtd">

	<log-service verbose="true" defaultElement="out">
<!-- Debug Error Info -->
		<log-service-config name="aml.monitoring.log" deploy="true" loadOnStartup="100" verbose="true" lastModified="1254285236109" target="all.web">
			<log-location>ONLY_CONSOLE</log-location>
			<log-level>Debug</log-level>
			 <log-directory>D:/log</log-directory>
			<max-log-size>1024</max-log-size>
			<show-prefix>true</show-prefix>
			<check-param>false</check-param>
			<!-- <log-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</log-param> -->
		</log-service-config>

		<log-service-config name="out" deploy="true" loadOnStartup="100" verbose="true" lastModified="1254285222843" target="all.web">
			<log-location>ONLY_CONSOLE</log-location>
			<log-level>Debug</log-level>
			<log-directory>D:/log</log-directory>
			<max-log-size>1024</max-log-size>
			<show-prefix>true</show-prefix>
			<check-param>false</check-param>
			<!-- <log-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</log-param> -->
		</log-service-config>

		<log-service-config name="workflow.engine.log" deploy="true" loadOnStartup="100" verbose="true" lastModified="1254285222843" target="all.web">
			<log-location>ONLY_CONSOLE</log-location>
			<log-level>Error</log-level>
			<log-directory>D:/log</log-directory>
			<max-log-size>1024</max-log-size>
			<show-prefix>true</show-prefix>
			<check-param>false</check-param>
			<!-- <log-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</log-param> -->
		</log-service-config>
        
        <log-service-config name="aml.kyc.log" deploy="true" loadOnStartup="100" verbose="true" lastModified="1511850926636" target="all.web">
            <log-location>ONLY_CONSOLE</log-location>
            <log-level>Debug</log-level>
            <log-directory>D:/log</log-directory>
            <max-log-size>1024</max-log-size>
            <show-prefix>true</show-prefix>
            <check-param>false</check-param>
            <log-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</log-param>
        </log-service-config>
        
        <log-service-config name="aml.debug.log" deploy="true" loadOnStartup="100" verbose="true" lastModified="1511850943541" target="all.web">
            <log-location>ONLY_CONSOLE</log-location>
            <log-level>Debug</log-level>
            <log-directory>D:/log</log-directory>
            <max-log-size>1024</max-log-size>
            <show-prefix>true</show-prefix>
            <check-param>false</check-param>
          <!--   <log-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</log-param> -->
        </log-service-config>
        
        <log-service-config name="common.admin.log" deploy="true" loadOnStartup="100" verbose="true" lastModified="1511851220760" target="all.web">
            <log-location>ONLY_CONSOLE</log-location>
            <log-level>Debug</log-level>
            <log-directory>D:/log</log-directory>
            <max-log-size>1024</max-log-size>
            <show-prefix>true</show-prefix>
            <check-param>false</check-param>
           <!--  <log-param>
				<param-name>transaction-isolation</param-name>
				<param-value>2</param-value>
			</log-param> -->
        </log-service-config>
        
	</log-service>
