=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/schema/session-service.dtd
<!ELEMENT session-service (session-service-config*)>
<!ELEMENT session-service-config (log-type, log-level, log-location,session-attribute-modification, session-location, session-replication, session-element-param+, description?)>
<!ELEMENT log-type (#PCDATA)>
<!ELEMENT log-level (#PCDATA)>
<!ELEMENT log-location (#PCDATA)>
<!ELEMENT session-attribute-modification (#PCDATA)>
<!ELEMENT session-location (#PCDATA)>
<!ELEMENT session-replication (#PCDATA)>
<!ELEMENT session-element-param (param-name, param-type)>
<!ELEMENT param-type (#PCDATA)>

<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST session-service
	defaultElement CDATA #IMPLIED
	verbose (true | false) 'false'>
	
<!ATTLIST session-service-config
	name CDATA #REQUIRED
	deploy (true | false) 'false'
	loadOnStartup CDATA #IMPLIED
	verbose (true | false) 'false'
	lastModified CDATA #IMPLIED
	target CDATA #IMPLIED>

=== wnstjqaodls/aml-project-meritz/TalkFile_aml_20251204_extracted/RBA/META-INF/config/session-service.xml
<?xml version="1.0" encoding="euc-kr"?>
<!-- UTF-8 처리 -->

<!DOCTYPE session-service SYSTEM "session-service.dtd">

	<session-service verbose="true" defaultElement="default">

		<session-service-config name="default" deploy="true" loadOnStartup="100" verbose="true" lastModified="1150350868953" target="all.web">
			<log-type>ONLY_CONSOLE</log-type>
			<log-level>DEBUG</log-level>
			<log-location></log-location>
			<session-attribute-modification>false</session-attribute-modification>
			<session-location>default</session-location>
			<session-replication>false</session-replication>
			<session-element-param>
				<param-name>password</param-name>
				<param-type>java.lang.String</param-type>
			</session-element-param>
			<session-element-param>
				<param-name>name</param-name>
				<param-type>java.lang.String</param-type>
			</session-element-param>
			<session-element-param>
				<param-name>userId</param-name>
				<param-type>java.lang.String</param-type>
			</session-element-param>
		</session-service-config>


		<session-service-config name="exam_session" deploy="true" loadOnStartup="100" verbose="true" lastModified="1216180885140" target="all.web">
			<log-type>NOT_LOGGING</log-type>
			<log-level>ERROR</log-level>
			<log-location></log-location>
			<session-attribute-modification>true</session-attribute-modification>
			<session-location>exam_session</session-location>
			<session-replication>false</session-replication>
			<session-element-param>
				<param-name>name</param-name>
				<param-type>java.lang.String</param-type>
			</session-element-param>
			<session-element-param>
				<param-name>count</param-name>
				<param-type>java.lang.String</param-type>
			</session-element-param>
		</session-service-config>


	</session-service>
